# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Delete 44
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Contact info
name: Anthony Davies
avatar: https://s.gravatar.com/avatar/27daea5cb28598ef30526f1586d9affb
email: daviesanthonye1234@gmail.com

# Build settings
markdown: kramdown

# Markdown formatter
kramdown:
  parse_block_html: true

date-format: '%B %d, %Y'

# Collections
collections_dir: collections

collections:
  blog-posts:
    output: true
  sections:
    output: false

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
