# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Delete 44
description: >- # this means to ignore newlines until "baseurl:"
  A digital portfolio and collection of blog posts for and by Anthony,
  a software developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.delete44.com" # the base hostname & protocol for your site, e.g. http://example.com

# Contact info
name: Anthony
avatar: https://s.gravatar.com/avatar/27daea5cb28598ef30526f1586d9affb
alt: A picture of the site author, Anthony

# Build settings
markdown: kramdown

# Markdown formatter
kramdown:
  parse_block_html: true

date-format: "%B %d, %Y"

# Collections
collections_dir: collections

collections:
  blog-posts:
    output: true
  sections:
    output: false
  rails-with-vue:
    output: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
